- name: 'Instalando o Docker'
  shell: 'curl -fsSL https://get.docker.com | bash'

- name: 'Adicionando as chaves do repositório apt do K8S'
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

-name: 'Adicionando repositório K8S'
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present

-name: 'Instalando pacotes: kubeadm + kubelet + kubectl'
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - kubelet
    - kubeadm
    - kubectl