- name: Criando Security Group
  local_action:
    module: ec2_group
    name: "{{ sec_group_name }}"
    description: "{{ sec_group_description }}"
    profile: "{{ profile }}"
    vpc_id: "{{ vpc_id }}"
    region: "{{ region }}"
    aws_secret_key: "{{ aws_secret_key }}"
    aws_access_key: "{{ aws_access_key }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 10.0.0.0/8
        rule_desc: SSH
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
  register: basic_firewall

- name: Criando EC2 Instace
  local_action:
    module: ec2
    group: {{ sec_group_name }}
    instance_type: {{ instace_type }}
    image: {{ image }}
    profile: {{ profile }}
    wait: true
    region: {{ region }}
    keypair: {{ keypair }}
    count: {{ count }}
  register: ec2

- name: Adicionando intância ao inventário temporário
  add_host: 
    name: {{ item.public_ip }}
    groups: "temp_group"
  with_items: "{{ ec2.instances }}"

- name: Adicionando instância ao inventário de hosts
  local_action:
  module: lineinfile
    dest: "../../hosts"
    regexp: {{ item.public_ip }}
    insertafter: "[kubernetes]" line: {{ item.public_ip }}
  with_items: "{{ ec2.instances }}"




    